Repository shahafashash/dnd-vtt, pull requests merged in 2023-09, with the labels that each got.

#1 font class
  .gitignore
  assets/Font/Font77.png
  assets/Font/Font77_selected.png
  assets/Font/Fonts.json
  font.py
  gui.py
  main.py
Labels: enhancement, help wanted, good first issue, wontfix

#3 Fix memory leaks
  loader.py
  main.py
  utils.py
Labels: enhancement

#7 Reduced loading time of loader to less than 1 sec for ~300 maps
  gui.py
  loader.py
  searchers.py
Labels: performance

#17 Refactored backend code, added downloader and new maps. Closes #10 Closes #12 Closes #13 Closes 14 Closes #15
  .gitignore
  Tools/downloader.py
  Tools/profilers.py
  Tools/utils.py
  backend/config.py
  backend/factories.py
  backend/loader.py
  backend/save_restore.py
  backend/searchers.py
  backend/serializers.py
  gui.py
  loader.py
  main.py
  maps.json
Labels: enhancement, refactor

#26 Added settings class to handle, save and load game settings. Closes #25
  backend/config.py
  backend/factories.py
  backend/settings.py
  main.py
  maps.json
  requirements.txt
  settings.json
  tools/downloader.py
Labels: enhancement

#27 Added map renaming option to menu. Closes #24
  backend/config.py
  frontend/menus.py
  main.py
Labels: enhancement
